---
services:
  donetick:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: donetick-local:latest
    container_name: donetick
    restart: unless-stopped

    volumes:
      - ./data:/donetick-data
      - ./config:/config

    ports:
      - "2021:2021"
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
      - TZ=America/Chicago
    hostname: donetick
networks:
  default:
